# Generated by Django 6.0.3 on 2026-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id_cobro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('referencia_pago', models.CharField(max_length=150, unique=True)),
                ('estatus', models.CharField(max_length=1)),
                ('fecha_cobro', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'cobro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('pk', models.CompositePrimaryKey('id_carrito', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('pk', models.CompositePrimaryKey('id_orden', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('precio_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('pk', models.CompositePrimaryKey('id_pedido', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('precio_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estatus', models.CharField(max_length=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('total_orden', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion_envio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_compra', models.DateField()),
                ('estatus', models.CharField(max_length=1)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.BooleanField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeccionExtranet',
            fields=[
                ('id_seccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo_pagina', models.CharField(max_length=100)),
                ('imagen_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_bienvenida', models.TextField(blank=True, null=True)),
                ('estatus', models.BooleanField()),
                ('url_destino', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'seccion_extranet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField()),
                ('rfc_proveedor', models.CharField(blank=True, help_text='Solo aplica para usuarios con rol 4 (Extranet)', max_length=13, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
