# Generated by Django 6.0.4 on 2026-05-21 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estatus', models.CharField(max_length=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('total_orden', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion_envio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_compra', models.DateField()),
                ('estatus', models.CharField(max_length=1)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(13)])),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id_cobro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('referencia_pago', models.CharField(max_length=150, unique=True)),
                ('estatus', models.CharField(max_length=1)),
                ('fecha_cobro', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_orden', models.OneToOneField(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.orden')),
            ],
            options={
                'db_table': 'cobro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.BooleanField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.categoria')),
                ('rfc', models.ForeignKey(blank=True, db_column='rfc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.proveedor')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('pk', models.CompositePrimaryKey('id_pedido', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('precio_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('pk', models.CompositePrimaryKey('id_orden', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('precio_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(max_length=1)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.orden')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.producto')),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('pk', models.CompositePrimaryKey('id_carrito', 'id_producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.producto')),
            ],
            options={
                'db_table': 'detalle_carrito',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='rfc',
            field=models.ForeignKey(db_column='rfc', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.proveedor'),
        ),
        migrations.CreateModel(
            name='SeccionExtranet',
            fields=[
                ('id_seccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo_pagina', models.CharField(max_length=100)),
                ('imagen_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_bienvenida', models.TextField(blank=True, null=True)),
                ('estatus', models.BooleanField()),
                ('url_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('portal_destino', models.CharField(default='4', max_length=1)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.usuario')),
            ],
            options={
                'db_table': 'seccion_extranet',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.usuario'),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.usuario'),
        ),
    ]
