# Generated by Django 6.0.3 on 2026-05-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionextranet',
            name='portal_destino',
            field=models.CharField(default='4', max_length=1),
        ),
    ]
