# Generated by Django 6.0.3 on 2026-05-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_seccionextranet_portal_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rfc',
            field=models.ForeignKey(blank=True, db_column='rfc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mascotas.proveedor'),
        ),
    ]
