# Generated by Django 6.0.4 on 2026-05-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_producto_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.usuario'),
        ),
    ]
