# Generated by Django 6.0.4 on 2026-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
