# Generated by Django 6.0.4 on 2026-05-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_proveedor_activo_alter_proveedor_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
