"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
import cloudinary
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('django-insecure-e3sb9wi8&0dgn@b!d9#+xrv*swk04u_a&z6oc+4jlne&xd$i5', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['proyecto-e-commerce-ventasperrunas.onrender.com', 'localhost', '127.0.0.1']

# --- SOLUCIÓN PARA EL ERROR DE "MIXED CONTENT" EN EL CARRITO ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "rest_framework",
    "corsheaders",
    "mascotas",
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Abrimos los CORS por completo para evitar bloqueos
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Permitimos cualquier subdominio de Vercel y el propio Render
CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    "https://proyecto-e-commerce-ventasperrunas.onrender.com",
    "http://localhost:3000",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres.lebbqfhcmicvhvutxovu",
        "PASSWORD": "Morgado9090@",
        "HOST": "aws-1-us-east-1.pooler.supabase.com",
        "PORT": "6543",
        'OPTIONS': {
            'options': '-c search_path=public'
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# ==============================================================================
# CONFIGURACIÓN PARA ENVÍO DE CORREOS REALES
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'                
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False    # Cambia a False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'sans15cadena@gmail.com' 
EMAIL_HOST_PASSWORD = 'fkni zfmj cplt mfhg' 
DEFAULT_FROM_EMAIL = 'Ventas Perrunas <sans15cadena@gmail.com>'

# 🔥 CORRECCIÓN: Claves de Cloudinary directas para que suban las imágenes
cloudinary.config(
    cloud_name = 'dusyqmcav',
    api_key = '114311678134825',
    api_secret = 'R6YsHsf0F3NzfgrBH9pi6MIqvnQ'
)